#for development
name: links-organizer

services:
  db:
    build: ./postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  node-dev:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: abcdefghijklmn
      NODE_PORT: ${NODE_PORT}
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    volumes:
      - ./postgres/schema_dump.sql:/app/postgres
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  react-dev:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      node-dev:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app

volumes:
  pgdata:
